database:
  address: 'jdbc:mysql://address:port/database'
  username: 'username'
  password: 'password'
  serverTablePrefix: 'mainserver'

defaults:
  world_name: 'world'
  pollFrequencySeconds: 60
  # will log the amount of time taken to poll the heatmap to the command/function caller
  # (i.e. if a player called the poll function, they will receive the message, otherwise the console)
  logPollTime: true
  pollAreaChunkSize: 1
  # if the poll range in seconds for a layer is set to this value, it will never update (after being created)
  # make sure this will never occur in practice by accident
  # value = INT_MAX
  noUpdatePollRangeSeconds: 2147483647
  # the date that all points will poll afterwards. The range is from (now-defaultPollRangeSeconds, now)
  # if the poll range is not given by a command/parameter (i.e. this is the default)
  # value = INT_MAX-1
  pollRangeSeconds: 2147483646
  # If a command with "divisionCount" is ran with a number greater than this, a warning will be sent to the command sender
  divisionDensityWarningCount: 128

colors:
  # https://cssgradient.io/ for the gradients
  cellActivityGradient: '#0F7299,#57C785,#EDDD53,#FF4400'
  cellOpacity: 0.50
  borderColor: '#E0E0E0'
  borderOpacity: 0.70
  heatmapBaseLayerColor: '#0F7299'
  heatmapBaseLayerOpacity: 0.05

# to disable, enter 0, otherwise, the weight will be added per action
activityWeights:
  # The minimum amount of activity for activity to be added to the database
  minimumActivityForRecording: 5
  playerPlace: 1
  playerBreak: 1
  playerSetSpawn: 1.5
  playerBedEnter: 0.5
  playerLeaveBed: 0
  playerChangeBeaconEffect: 1
  playerChangedWorldEvent: 1
  playerFishEvent: 0
  playerFlowerPotManipulateEvent: 0.5
  playerArmorStandManipulateEvent: 0.5
  playerHarvestBlockEvent: 0.75
  playerInsertLecternEvent: 0
  playerItemFrameChangeEvent: 0
  playerPurchaseEvent: 0.25
  playerShearBlockEvent: 1
  playerShearEntityEvent: 0
  playerTakeLecternBookEvent: 0
  playerInteractChestEvent: 1
  playerInteractBarrelEvent: 1
