database:
  address: "jdbc:mysql://address/database"
  username: "username"
  password: "password"

defaults:
  world_name: "world"
  pollFrequencySeconds: 60
  pollAreaChunkSize: 1

colors:
  #https://cssgradient.io/ for the gradients
  cellActivityGradient: "#0F7299,#0F7299,#EDDD53"
  cellOpacity: 0.60
  borderColor: "#E0E0E0"
  borderOpacity: 0.70
